### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by draphago** [aschmelyun/use-the-keyboard#104]
Sorry I'm new in github. Its a feature request. I want to have a shortcut for send message without sound. 

Background information: I have a friend and he has issues with sleeping phases. So after he goes bed I want to send him only silent messages but accidentally every time I forget to right click the send button and click on "send without sound".

**Comment by draphago** [comment]
Or please forward it or me to the right team.

**Comment by aschmelyun** [comment]
Hi, sorry! You'll have to contact the developers of the application itself, I'm just the creator of the keyboard shortcuts page for it. Wish I could be more help!
