### ISSUE TITLE
Apple Music

### ISSUE THREAD

**Issue by votqanh** [aschmelyun/use-the-keyboard#113]
Adding this would be really nice: https://support.apple.com/guide/music/keyboard-shortcuts-mus1019/mac

**Comment by aschmelyun** [comment]
@votqanh Thanks for the suggestion! Those shortcuts are now active at [usethekeyboard.com/apple-music](https://usethekeyboard.com/apple-music)

**Comment by votqanh** [comment]
Thank you!
