### ISSUE TITLE
notion ctrl + shift + 4 does not create a todo list

### ISSUE THREAD

**Issue by avaramis** [aschmelyun/use-the-keyboard#42]
I was excited to find the answer to my desire to convert a line into a todo list with keyboard shortcuts only what "use-the-keyboard" indicates either needs further clarification or has been rendered out of date by a notion update.
Before hitting ctrl + shift + 4 I tried:

- placing the cursor at the beginning of the line
- creating a new line
- using the 4 from the numpad
- ctrl + shift on the LH and the/or the RH side of my keyboard (this matters in PICO on linux)
- downloading the desktop app

ATC, I have a feeling that they might have changed this out from under you

**Comment by mcmevans** [comment]
@avaramis this shortcut works a treat for me. Sorry it doesn't work for you, but doesn't seem to be an issue with ATC.

You may be aware already but another shortcut you could try to turn an existing line into a to-do is:
- navigate to the start of the line
- Type [] (left square bracket, then right square bracket)

**Comment by avaramis** [comment]
[] square brackets at the beginning of the line does work, but it's
unfortunate that the hot keys don't.
I just retried and it's still a problem for me.
I can imagine how hard it must be to trouble shoot a thing like this.
Almost need to support custom assignment of keystrokes to establish a place
where a variety of keystrokes could be observed for their impact and either
worked around or dealt with.

**Comment by aschmelyun** [comment]
I've been able to verify this shortcut working on both the standalone Windows app as well as the web app. Please let me know if you're still experiencing an issue with Ctrl + Shift + 4 not creating a to-do list item.
