### ISSUE TITLE
Add CryptoCRIT

### ISSUE THREAD

**Issue by theabbie** [aschmelyun/use-the-keyboard#73]
The Keyboard Shortcuts are

`CTRL + ALT + F1` for settings
`CTRL + ALT + F2` for Home
`CTRL + ALT + F3` for Dark mode
`CTRL + ALT + F4` for Exit

**Comment by aschmelyun** [comment]
In order to be included on usethekeyboard.com, there will need to be a live website or downloadable app available. If that changes, please let me know!
