### ISSUE TITLE
Todoist shortcut key overrides Gaelic language key

### ISSUE THREAD

**Issue by Klerie** [aschmelyun/use-the-keyboard#80]
Alt Gr is  á in my Irish Gaelic writing - until I installed "Todoist"..
Todoist has inserted this shortcut key automatically to launch Todoist Today.
How can I cancel this shortcut?

**Comment by aschmelyun** [comment]
I'm not sure if there's a way to do this. I'm unfortunately not affiliated with Todoist, but your best bet would be to reach out to the developers on their [contact page here](https://todoist.com/contact) and try to resolve your issue that way!
